[tool.poetry]
name = "spotipy-podcasts"
version = "0.1.0"
description = ""
authors = ["vvveracruz <me@vgg.cz>"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
